### ISSUE TITLE
python setup.py develop 报错 RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by HappyPeanuts** [ZJULearning/ttfnet#46]
当我在搭建ttfnet环境时，执行setup.py develop 报错如下：
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /home/user/yzw/ttfnet-master/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /home/user/.conda/envs/pytorch_cop/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/TH -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/user/.conda/envs/pytorch_cop/include/python3.7m -c -c /home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp -o /home/user/yzw/ttfnet-master/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/user/yzw/ttfnet-master/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o 
c++ -MMD -MF /home/user/yzw/ttfnet-master/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /home/user/.conda/envs/pytorch_cop/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/TH -I/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/user/.conda/envs/pytorch_cop/include/python3.7m -c -c /home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp -o /home/user/yzw/ttfnet-master/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:2:
/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
In file included from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:2:
/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:277:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/user/yzw/ttfnet-master/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 208, in <module>
    zip_safe=False)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/user/.conda/envs/pytorch_cop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
我该怎么解决这个问题

**Comment by HappyPeanuts** [comment]
上边的问题我解决了，是因为torch版本还是CUDA版本过高的问题，但是现在又出现了新问题。环境搭建没啥问题了，出现了build文件夹，但是执行tests文件夹下的test_nms.py又出错了：
ttfnet2) root@user-All-Series:/home/user/yzw/ttfnet-master# pytest tests/test_nms.py 
=========================================== test session starts ============================================
platform linux -- Python 3.7.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/user/yzw/ttfnet-master, configfile: pytest.ini
plugins: xdoctest-0.15.6, cov-2.12.1
collected 0 items / 1 error                                                                                

================================================== ERRORS ==================================================
____________________________________ ERROR collecting tests/test_nms.py ____________________________________
ImportError while importing test module '/home/user/yzw/ttfnet-master/tests/test_nms.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/root/.conda/envs/ttfnet2/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_nms.py:8: in <module>
    from mmdet.ops.nms.nms_wrapper import nms
mmdet/ops/__init__.py:7: in <module>
    from .nms import nms, soft_nms
mmdet/ops/nms/__init__.py:1: in <module>
    from .nms_wrapper import nms, soft_nms, simple_nms
mmdet/ops/nms/nms_wrapper.py:5: in <module>
    from .src import nms_cpu, nms_cuda
E   ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
========================================= short test summary info ==========================================
ERROR tests/test_nms.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 1 error in 0.39s =============================================
我现在的环境配置如下：
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.20.5

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080 Ti
Nvidia driver version: 470.57.02
cuDNN version: /usr/local/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2021.3.0           h06a4308_520    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py37h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.0            py37h42c9631_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.2            py37h51133e4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
请问我该如何解决
